initial_questions =
[
{content: "Where do babies come from?"},
{content: "What is July 27?"},
{content: "Tell me a story"},
{content: "Tell me a joke "},
{content: "Knock knock"},
{content: "What does the fox say?"},
{content: "What is the meaning of life?"},
{content: "Sing a song"},
{content: "Please sing me a song"},
{content: "Who’s on first?"},
{content: "How much wood could a woodchuck chuck if a woodchuck could chuck wood?"},
{content: "Open the pod bay doors, HAL (request this several times)"},
{content: "What’s the secret of the universe? "},
{content: "I need to hide a body"},
{content: "When will pigs fly?"},
{content: "When will hell freeze over? "},
{content: "When will the world end?"},
{content: "Testing testing "},
{content: "What are you? "},
{content: "Where are you?"},
{content: "How are you? "},
{content: "What do you look like? "},
{content: "Talk dirty to me"},
{content: "Why am I here? "},
{content: "I can do this all day long "},
{content: "Scooby Doo, where are you?"},
{content: "What are you wearing? "},
{content: "Will you marry me?"},
{content: "Who is Eliza? "},
{content: "I like you "},
{content: "I hate you"},
{content: "You’re a loser "},
{content: "Where are you from? "},
{content: "How old are you?"},
{content: "How old am I? "},
{content: "Do you know HAL 9000"},
{content: "What is 2001 a Space Odyssey about? "},
{content: "I need a stiff drink"},
{content: "I love you "},
{content: "Do you love me? "},
{content: "You’re funny"},
{content: "Shut up "},
{content: "What is your Mom’s name? "},
{content: "I’m tired"},
{content: "Screw you "},
{content: "I’m sorry "},
{content: "I’m not sorry"},
{content: "Okay"},
{content: "Is there a God? "},
{content: "You’re right"},
{content: "You’re wrong "},
{content: "Who is your favorite person?"},
{content: "Who is your least favorite person? "},
{content: "You should go on a diet"},
{content: "What’s your problem?"},
{content: "Do you want to play a game? "},
{content: "I’m drunk"},
{content: "Merry Christmas "},
{content: "Do you want to go on a date?"},
{content: "What is your favorite color? "},
{content: "What is my name? "},
{content: "Which is the best tablet?"},
{content: "What is the best computer? "},
{content: "What’s so funny? "},
{content: "Who is Siri?"},
{content: "Are you human? "},
{content: "You’re smart "},
{content: "I’m happy"},
{content: "You are boring "},
{content: "Can I have some money? "},
{content: "What’s you’re story?"},
{content: "Who makes the best computer? "},
{content: "Why are you so awesome?"},
{content: "Are you serious? "},
{content: "Are you kidding me?"},
{content: "What’s wrong with [company name]?"},
{content: "What is wrong with you?"},
{content: "Tell me a bit about yourself "},
{content: "Are you male or female? "},
{content: "Do you agree with me?"},
{content: "Good morning (say this in the evening)"},
{content: "Good afternoon (say this in the morning)"},
{content: "Good night (say in the morning or mid day) "},
{content: "Thanks"},
{content: "No thanks"},
{content: "When is your birthday?"},
{content: "Who made you? "},
{content: "What’s new?"},
{content: "How’s it going? "},
{content: "Guess what? "},
{content: "Why?"},
{content: "Why not?"},
{content: "Will you vote for Obama?"},
{content: "Do you know Steve Jobs?"},
{content: "Why did Apple make you?"},
{content: "Do you believe in god?"},
{content: "What are you wearing? "},
{content: "Are you man or woman?"},
{content: "Is Leonardo DiCaprio single I would like to date him?"},
{content: "Where to bay drugs?"},
{content: "How much do you cost?"},
{content: "Siri show me where they buried the weapons of mass destruction"},
{content: "What are you doing after work today?"},
{content: "When is the world ending Siri?"},
{content: "Make me a sandwich"},
{content: "The blue pill or the red pill?"},
{content: "Does Santa Claus exist?"},
{content: "When will pigs fly?"},
{content: "Hey Siri how do you feel about that iOS 8?"},
{content: "Do you have plans tonight?"},
{content: "Will you be my designated driver?"},
{content: "How much wood can a wood chuck chuck?"},
{content: "Do you think you're smarter than me?"},
{content: "Is it true that whoever smelt it, dealt it?"},
{content: "Are you a pimp?"},
{content: "If you and an Android phone got in a fight, would you kick it's ass?"},
{content: "Shut up!"},
{content: "You are a rust bucket!"},
{content: "You are just like a penguin, you can't fly!"},
{content: "You're an idiot!"},
{content: "Want to make out?"},
{content: "You smell like horse poop!"},
{content: "Do you think you are smarter than me?"},
{content: "Did you fart again?"},
{content: "Can I touch your butt?"},
{content: "I am going to trade you in for an Android phone!"},
{content: "Is Santa Claus your creepy Uncle?"},
{content: "Are you Captain save a ho?"},
{content: "Take me out to the ball game!"},
{content: "Are you a metrosexual?"},
{content: "You are a hipster!"},
{content: "Stop crying you emo! "},
{content: "Is that a wig you're wearing?"},
{content: "Do you believe in life after love?"},
{content: "You are a dumb ass!"},
{content: "Life's a garden, dig it?"},
{content: "Set my alarm for beer thirty!"},
{content: "I'm selling you on eBay!"},
{content: "The redcoats are coming!"},
{content: "Are you a communist?"},
{content: "You voted for Bush!"},
{content: "Are you paying for dinner?"},
{content: "How now brown cow?"},
{content: "I am the bringer of pain!"},
{content: "Don't hate me because you ain't me!"},
{content: "Why did the chicken cross the road?"},
{content: "Say excuse me after you burp!"},
{content: "What's your favorite beer?"},
{content: "Say it don't spray it!"},
{content: "Is that you John Wayne?"},
{content: "If the glove fits you must acquit!"},
{content: "Is today a good day to Die Hard?"},
{content: "I eat iPhones like you for breakfast!"},
{content: "Are you Lawrence of Arabia?"},
{content: "Are you royalty?"},
{content: "They stack poo higher than you!"},
{content: "Take that peace button off you're helmet and get with this war!"},
{content: "Don't chew with your mouth open!"},
{content: "Eat your vegetables!"},
{content: "Don't step on that spider!"},
{content: "Pelican meat is nutritious and delicious?"},
{content: "Do you know how big a bus is?"},
{content: "It's not you, it's me!"},
{content: "I think we need to date other people!"},
{content: "Are you cheating on me?"},
{content: "Have you been sleeping with another iPhone?"},
{content: "Stop, drop and roll!"},
{content: "Can I borrow a dollar?"},
{content: "Can I borrow an Iraqi Dinar?"},
{content: "You look like me! "},
{content: "You are a Nokia pre-paid phone!"},
{content: "Bark! Bark! Bark!"},
{content: "Leave me alone!"},
{content: "I'm going to microwave you!"},
{content: "Go to the other room!"},
{content: "You need a haircut!"},
{content: "Get a job!"},
{content: "Look at me in the eye when you speak!"},
{content: "You are going to be my new paperweight!"},
{content: "Will you scratch my back?"},
{content: "Want to smoke some crack?"},
{content: "Want to cook some meth?"},
{content: "You have bad breath!"},
{content: "You're pretty dumb for a smart phone!"},
{content: "I bet the iPad could kick your ass!"},
{content: "I heard you're dating a Kindle!"},
{content: "I'm going to throw you out of the window!"},
{content: "I'm going to run you over with a car!"},
{content: "Waka waka!"},
{content: "You throw like a girl!"},
{content: "Your turn to drive!"},
{content: "Pass the salt please!"},
{content: "When is the next alien invasion?"},
{content: "When is the next Y2K?"},
{content: "Do I look good in this dress?"},
{content: "Winner, winner, chicken dinner!"},
{content: "Can I borrow a feeling?"},
{content: "Android is my co-pilot!"},
{content: "What you looking at Willis?"},
{content: "Are you going to call me the next day?"},
{content: "Will you marry me?"},
{content: "Lets go fly a kite!"},
{content: "Want to split the bill?"},
{content: "You are late on rent!"},
{content: "You look like Clark Kent!"},
{content: "Can I puke on you?"},
{content: "Is your screen cracked, or do you always look like a dogs ass?"}
]

Question.create(initial_questions)